### ISSUE TITLE
Test case should be modified.

### ISSUE THREAD

**Issue by ikixxx** [murphydanger/minify-css-sourcemaps-error#1]
I've just checkout your project, midifed html to this:
````html
    <body>
        <h1>style.css</h1>
        <p>
            Open Chrome DevTools and check if the source map fits...
            <span class="t1">
              <span>
                  <span class="t2">
                      <span>Lorem ipsum dolor sit amet,
 consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
 Ut enim ad minim veniam, quis nostrud exercitation ullamco .</span>
            </span>
        </span>
      </span>
        </p>
    </body>
````

and for scss:

````scss
@import "_partial";

body {
    color: $red;
    p {
          .t1 {
            .t2{
              span {
                font-weight: bold;
                color:red;
              }
            }
          }

    }
}

````

If you look at the innermost `span` element. It will say the code that make it  **red** is on line **3**.
And if you click on the script it will drop you on line **3** inside the chrome editor (line with body tag declaration)
